//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reiner.AttackServiceRefernce {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AttackServiceRefernce.ISecretariatService")]
    public interface ISecretariatService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecretariatService/CheckConnection", ReplyAction="http://tempuri.org/ISecretariatService/CheckConnectionResponse")]
        string CheckConnection();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecretariatService/CheckConnection", ReplyAction="http://tempuri.org/ISecretariatService/CheckConnectionResponse")]
        System.Threading.Tasks.Task<string> CheckConnectionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecretariatService/TestURL", ReplyAction="http://tempuri.org/ISecretariatService/TestURLResponse")]
        string TestURL(string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecretariatService/TestURL", ReplyAction="http://tempuri.org/ISecretariatService/TestURLResponse")]
        System.Threading.Tasks.Task<string> TestURLAsync(string url);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISecretariatServiceChannel : Reiner.AttackServiceRefernce.ISecretariatService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SecretariatServiceClient : System.ServiceModel.ClientBase<Reiner.AttackServiceRefernce.ISecretariatService>, Reiner.AttackServiceRefernce.ISecretariatService {
        
        public SecretariatServiceClient() {
        }
        
        public SecretariatServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SecretariatServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecretariatServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecretariatServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CheckConnection() {
            return base.Channel.CheckConnection();
        }
        
        public System.Threading.Tasks.Task<string> CheckConnectionAsync() {
            return base.Channel.CheckConnectionAsync();
        }
        
        public string TestURL(string url) {
            return base.Channel.TestURL(url);
        }
        
        public System.Threading.Tasks.Task<string> TestURLAsync(string url) {
            return base.Channel.TestURLAsync(url);
        }
    }
}
